AWSTemplateFormatVersion: '2010-09-09'
Description: Adds Secrets Manager access policy to an existing IAM role

Parameters:
  ExistingRoleName:
    Type: String
    Description: Name of the existing IAM role to attach the policy to
    Default: EC2-AppConfig-User-Agent

Resources:
  # Inline policy attached to the existing role
  AppConfigSecretsManagerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SecretsManager-GetDevElasticsearchSecret
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: 
              - arn:aws:secretsmanager:us-west-2:638891785980:secret:dev/elasticsearch-*
              - arn:aws:secretsmanager:us-west-2:638891785980:secret:dev/postgress-*
              - arn:aws:secretsmanager:us-west-2:638891785980:secret:sam_sync-*
      Roles:
        - !Ref ExistingRoleName
